spring:
  application:
    name: microservice-bank-discovery
eureka:
  instance:
    prefer-ip-address: true
    hostname: http://bank-discovery.crexfme8bye6evhu.eastus.azurecontainer.io
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
