eureka:
  instance:
    prefer-ip-address: true
    hostname: bank-discovery
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      defaultZone: http://bank-discovery.crexfme8bye6evhu.eastus.azurecontainer.io/eureka

spring:
  application:
    name: microservice-passive-accounts
  data:
    mongodb:
      uri: mongodb+srv://csanmont:csanmont@cluster0.bxnzqcx.mongodb.net/BankPassiveAccounts?retryWrites=true&w=majority  
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration