server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    hostname: bank-discovery
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
      defaultZone: http://bank-discovery:8761/eureka


spring:
  application:
    name: microservice-bank-gateway
  cloud:
    gateway:
      routes:
        - id: microservice-customers
          uri: http://customers:8081
          predicates: 
          - Path=/person/**
        - id: microservice-passive-accounts
          uri: http://passive-accounts:8082
          predicates: 
          - Path=/passive-accounts/**, /movement/**, /debitcard/**, /wallet/**
        - id: microservice-credit-accounts
          uri: http://credit-accounts:8083
          predicates: 
          - Path=/credit/**, /creditMovements/**
        - id: microservice-wallet
          uri: http://wallet:8084
          predicates: 
          - Path=/wallet/**    
      discovery:
        locator:
          enabled: true
    loadbalancer:
      ribbon:
        enabled: false
          
 