server:
  port: 8888
spring:
  application:
    name: microservice-bank-config
  cloud:
    config:
      server:
        git:
          ignore-local-ssh-settings: true
          default-label: main
          uri: https://github.com/bootcamp50/microservice-bank-config.git
          search-paths: config-data